# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.0"

gem "graphql", "~> 1.8"

gem "rack", "~> 2.0"

gem "sinatra-contrib", "~> 2.0"

gem "rack-contrib", "~> 2.1"

gem "byebug", "~> 11.1"
